### PR TITLE
Removed services duplicated by ports in firewall config

### LINKED ISSUE #108: Duplicate ports in firewall config?
https://github.com/ManageIQ/manageiq-appliance-build/blob/master/kickstarts/partials/post/firewalld.ks.erb

@carbonin @abellotti Do we need ssh, http, https, postgres listed multiple times in the firewall config?

### PR DESCRIPTION
**Pull request by carbonin**
Fixes #108 

@bdunne @abellotti

### CODE REVIEW

**Comment by bdunne** [comment]
I'd prefer to see the port references go.  Having the named services clearly describes what is open and what service is using it in my opinion.

**Comment by bdunne** [comment]
cc @jrafanie @Fryguy

**Comment by carbonin** [comment]
The services only cover the tcp protocol on the listed ports so I wouldn't be able to just use the services. I could list the services then additionally add the same port with udp if that would be better.

**Comment by bdunne** [comment]
I don't think we actually need the UDP port, do we?

**Comment by carbonin** [comment]
No idea :sweat_smile:

**Comment by jrafanie** [comment]
> I don't think we actually need the UDP port, do we?

I hope we had a commit message that said why we used it.  I remember needing it for something, but I don't remember

**Comment by bdunne** [comment]
Apache should only be using TCP

**Comment by carbonin** [comment]
Just FYI the ports enabled by a particular service are defined in files in `/usr/lib/firewalld/services/`

**Comment by jrafanie** [comment]
I'd be good with removing UDP from the allowed ports if we run it on an appliance and can browse the UI and hit some rest api endpoints. :fire:

**Comment by carbonin** [comment]
Okay, I'll run a build for this branch.

**Comment by Fryguy** [comment]
@carbonin Any more on this PR?

**Comment by Fryguy** [comment]
@carbonin Bump?

**Comment by Fryguy** [comment]
@carbonin Is this darga yes/no?

**Comment by carbonin** [comment]
@Fryguy it's a no, it definitely isn't a bug.

**Comment by jrafanie** [comment]
🎉

**Pull request merged**
