### PR TITLE
Remove legacy symlinks as all code needs to load without them.

### PR DESCRIPTION
**Pull request by jrafanie**
- [x] Needs https://github.com/ManageIQ/manageiq-appliance/pull/33

### CODE REVIEW

**Comment by jrafanie** [comment]
cc @Fryguy @carbonin @simaishi Are we ready for this???

**Comment by carbonin** [comment]
https://github.com/ManageIQ/manageiq-appliance-build/pull/60

**Comment by chessbyte** [comment]
#60 is merged.  Please rebase and push again.

**Comment by jrafanie** [comment]
@carbonin @chessbyte Rebased after merge conflict.

**Comment by carbonin** [comment]
https://github.com/ManageIQ/manageiq-appliance/blob/master/LINK/usr/bin/appliance_console#L7
https://github.com/ManageIQ/manageiq-appliance/blob/master/LINK/usr/bin/appliance_console_cli#L15 - not as sure about this one
https://github.com/ManageIQ/manageiq-appliance/blob/master/LINK/usr/bin/evm_watchdog.rb#L5

Also need to be changed.

**Comment by jrafanie** [comment]
Thanks @carbonin, I'm fixing the referenced locations.  I'll submit a PR when I have them.

**Comment by kbrock** [comment]
@carbonin @jrafanie this is great stuff. thanks

**Comment by jrafanie** [comment]
@carbonin What do you think of removing this now?

**Pull request closed without merging**
