### PR TITLE
Specified only production dependencies be installed

### PR DESCRIPTION
**Pull request by chalettu**
SUI fix for appliance build.  Ensured we only install production dependencies

### CODE REVIEW

**Comment by chalettu** [comment]
Dependent on a SUI PR https://github.com/ManageIQ/manageiq-ui-service/pull/648

**Comment by Fryguy** [comment]
:+1:

**Comment by Fryguy** [comment]
@simaishi Do we do bundle install in production mode for the manageiq repo?  I can't find it anywhere.  I see RAILS_ENV is set in /etc/default/evm in the manageiq-appliance repo, but that's it.

**Comment by chriskacerguis** [comment]
👍

**Comment by chriskacerguis** [comment]
Wondering if we should set the NODE_ENV on the appliance?

**Comment by simaishi** [comment]
@Fryguy we do `bundle install` here: https://github.com/ManageIQ/manageiq-appliance-build/blob/master/kickstarts/partials/post/bundler.ks.erb#L12

**Comment by simaishi** [comment]
Confirmed working.  @chalettu Thanks!

**Pull request merged**
