### PR TITLE
Add an rpm dependency on openscap-scanner

### PR DESCRIPTION
**Pull request by moolitayer**

### CODE REVIEW

**Comment by moolitayer** [comment]
@jrafanie @carbonin @simon3z please review

**Comment by jrafanie** [comment]
@moolitayer  Looks good. Is this in the base centos OS repo or somewhere else?  For future reference, it's helpful to list the yum repo that a rpm can be found.

**Comment by moolitayer** [comment]
> @moolitayer Looks good. Is this in the base centos OS repo or somewhere else? For future reference, it's helpful to list the yum repo that a rpm can be found.

@jrafanie I believe it is in the base repo:
- http://mirror.centos.org/centos/6/os/x86_64/Packages/openscap-scanner-1.0.10-3.el6.centos.x86_64.rpm
- http://mirror.centos.org/centos/7/os/x86_64/Packages/openscap-scanner-1.2.5-3.el7.x86_64.rpm

**Comment by jrafanie** [comment]
LGTM, thanks @moolitayer, @simaishi @carbonin are you fine with this?

**Comment by simaishi** [comment]
Yes, looks good.

**Comment by carbonin** [comment]
:+1:

**Comment by jrafanie** [comment]
:tada:

**Pull request merged**
