### PR TITLE
Remove the temporary imagefactory meta and body files every few days.

### PR DESCRIPTION
**Pull request by jrafanie**
Please review @abellotti @brandondunne

### CODE REVIEW

**Comment by abellotti** [comment]
let's add that puppy as /build/bin/clean_imagefactory_storage.sh and update the doc so that the cron simply runs that script.  This way I can manually run the script by hand and not needed to setup cron on non-production build VMs.

**Comment by brandondunne** [comment]
:+1: LGTM

**Comment by kbrock** [comment]
:+1: yay clean all things!

**Comment by jrafanie** [comment]
Good idea @abellotti, done.  Please review.

**Comment by abellotti** [comment]
Looks Good. Thanks @jrafanie

**Pull request merged**
