### PR TITLE
Direct /dev/console to /dev/ttyS0 for openstack

### PR DESCRIPTION
**Pull request by jvlcek**
https://bugzilla.redhat.com/show_bug.cgi?id=1278084

### CODE REVIEW

**Comment by jvlcek** [comment]
I have marked this as a WIP PR because I'm in the process of building and testing a full image.
I'll remove the WIP once the fix has been tested.

**Comment by jvlcek** [comment]
@simaishi and @bdunne Please review

**Comment by kbrock** [comment]
Glad to see this openstack bug come full circle.

**Comment by jvlcek** [comment]
Removing WIP. Testing as described in BZ description succeeded.

**Comment by jvlcek** [comment]
I also tested to ensure the kickstarts are correctly generated for all targets.

**Comment by bdunne** [comment]
:+1:

**Comment by kbrock** [comment]
:tada: Very cool :tada:

**Pull request merged**
