### PR TITLE
Move compile assets, sti loader and SSUI from cfme-setup

### PR DESCRIPTION
**Pull request by simaishi**
Related PR: https://github.com/ManageIQ/manageiq-appliance/pull/67

### CODE REVIEW

**Comment by kbrock** [comment]
@simaishi safe to assume that you have run this on a build? - ok to merge? (aka LGTM)

**Comment by simaishi** [comment]
Yes, ran an appliance build successfully with this + manageiq-appliance change.

**Comment by kbrock** [comment]
On second glance, I think most of this does not belong in kickstart. Thought I realize that install the OS vs the app may be too nebulous.

build|dev|reasoning|example
---|---|---|---
[kickstart]|[guides]|setup os|Install OS, ruby, node, postgres (calls get app code)
[rpm]|[fetch]|download code|Get the app code, put down app files
[cfme-setup.sh]|[setup]|setup app|`bundle update`, `bower install`, `db:create db:migrate seed`
?|[update]|update app|`bundle install`, `db:migrate db:seed`

[rpm]: http://pkgs.devel.redhat.com/cgit/rpms/cfme/tree/cfme.spec?h=cfme-rh-ruby22-5.6-rhel-7
[kickstart]: https://github.com/ManageIQ/manageiq-appliance-build/blob/master/kickstarts/base.ks.erb
[cfme-setup.sh]: https://github.com/ManageIQ/manageiq-appliance/blob/master/cfme-setup.sh
[fetch]:https://github.com/ManageIQ/guides/blob/master/developer_setup.md#clone-the-code
[guides]: https://github.com/ManageIQ/guides/blob/master/developer_setup.md
[setup]: https://github.com/ManageIQ/manageiq/blob/master/bin/setup
[update]: https://github.com/ManageIQ/manageiq/blob/master/bin/update

@Fryguy does that table look right to you?

**Comment by Fryguy** [comment]
cfme-setup.sh is only run in the kickstart at the moment so moving it directly into kickstart seems fine to me. @kbrock Your table there seems to separate kickstart from rpm from cfme-setup by concern, but in reality they are *all* run in the kickstart.

**Comment by kbrock** [comment]
@Fryguy agreed, merging setup into kickstart probably makes sense.

But the user can still run `rpm update` - so we need to be able to handle that very common use case

**Comment by Fryguy** [comment]
downstream rpm updates are fine as we don't allow bower and bundler updates there (they are provided as part of the various RPMs).

**Pull request merged**
