### PR TITLE
Stop uploading to Rackspace

### PR DESCRIPTION
**Pull request by bdunne**
releases.manageiq.org now points to DigitalOcean

cc @simaishi

### CODE REVIEW

**Comment by simaishi** [comment]
Jansa backport details:

```
$ git log -1
commit 141fb0a474ce4f87c0825ca4a51a5cfcd91ecf73
Author: Jason Frey <fryguy9@gmail.com>
Date:   Tue Aug 18 18:11:01 2020 -0400

    Merge pull request #436 from bdunne/drop_rackspace_upload

    Stop uploading to Rackspace

    (cherry picked from commit de5f1ce18c982f94c2b0cbffb5ab0518855fad70)
```

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 142881517df3c2a8558310b42b3f6ac487e926d3
Author: Jason Frey <fryguy9@gmail.com>
Date:   Tue Aug 18 18:11:01 2020 -0400

    Merge pull request #436 from bdunne/drop_rackspace_upload

    Stop uploading to Rackspace

    (cherry picked from commit de5f1ce18c982f94c2b0cbffb5ab0518855fad70)
```

**Comment by chessbyte** [comment]
@bdunne @simaishi @Fryguy can we now delete everything from Rackspace?

**Comment by Fryguy** [comment]
That's the plan, yes.

**Pull request merged**
