### PR TITLE
Move and convert doc to readme as markdown

### PR DESCRIPTION
**Pull request by jrafanie**
There's a lot of cleanup to do but I think this makes it easier to read and find information if you land on the github repo page.

You can preview it here:  https://github.com/jrafanie/manageiq-appliance-build/tree/move_and_convert_doc_to_readme_markdown

### CODE REVIEW

**Comment by jrafanie** [comment]
The second commit is the actual conversion to markdown.

**Comment by kbrock** [comment]
:+1: LGTM

**Comment by jrafanie** [comment]
Thanks @kbrock

**Comment by jrafanie** [comment]
cc @abellotti (you'll probably be interested in this PR when you return)

**Comment by abellotti** [comment]
Nice !!  :cake:

**Comment by jrafanie** [comment]
:smile:

**Pull request merged**
