### PR TITLE
Upgrade to ruby 2.2.3.

### PR DESCRIPTION
**Pull request by jrafanie**
:sparkles: https://www.ruby-lang.org/en/news/2015/08/18/ruby-2-2-3-released/ :sparkles:

### CODE REVIEW

**Comment by jrafanie** [comment]
@abellotti Please review and merge.  Thanks!

**Comment by abellotti** [comment]
LGTM !!   :+1:

**Comment by kbrock** [comment]
homebrew/ruby-build note and reminder:

```
brew update
brew upgrade ruby-build
ruby-build 2.2.3 /opt/rubies/ruby-2.2.3
```

**Comment by jrafanie** [comment]
### For ruby-install people:
```
brew update
brew upgrade ruby-install
ruby-install ruby 2.2.3
```

### Bonus points:
```
brew upgrade # upgrade all brew packages
brew cleanup
```

**Pull request merged**
