### PR TITLE
Added pglogical packages and repos

### PR DESCRIPTION
**Pull request by carbonin**
Pull pglogical packages from copr repo.

@Fryguy @gtanzillo @jrafanie

### CODE REVIEW

**Comment by carbonin** [comment]
Should be merged with https://github.com/ManageIQ/manageiq-appliance/pull/57

**Comment by kbrock** [comment]
note: This needs to be merged **before** 57, not at the same time as 57. So just merge this and don't wait for turn key synchronization.

This is very exciting.

**Comment by carbonin** [comment]
@kbrock correct.  I'll make an edit.

**Comment by jrafanie** [comment]
Looks good

**Comment by jrafanie** [comment]
@carbonin should we hold off on merging this until nightlies are working again following the rails 5 update?

**Comment by carbonin** [comment]
I don't think it really matters ...

**Pull request merged**
