### PR TITLE
Explicitly specify branch even for 'master'

### PR DESCRIPTION
**Pull request by simaishi**
Then, BRANCH will be the only edit needed when we cut a new branch.

### CODE REVIEW

**Comment by simaishi** [comment]
@Fryguy please review

**Comment by simaishi** [comment]
Marking as WIP, as docbuild part needs to be changed as per #162

**Comment by simaishi** [comment]
Euwe PR: https://github.com/ManageIQ/manageiq-appliance-build/issues/164

**Comment by chessbyte** [comment]
Backported to Darga via PR #164 
```sh
$ git log
commit 3f537dda3a1e2f2d004986d7f25e36d790b3b945
Merge: f523c60 cc32f38
Author: Oleg Barenboim <chessbyte@gmail.com>
Date:   Fri Sep 30 03:33:09 2016 +0300

    Merge pull request #164 from simaishi/euwe_update_nightly
    
    [EUWE] Explicitly specify branch even for 'master'
```

**Pull request merged**
