### PR TITLE
[Changelog] Rollup of Ivanchuk releases

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label ivanchuk/yes

**Comment by simaishi** [comment]
"Remove pglogical package"

This belongs in `Removed` section, not `Added`.

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 660c0ffa286e996cc4af71624cdf72694a1d9e16
Author: Satoe Imaishi <simaishi@redhat.com>
Date:   Tue Sep 10 11:50:34 2019 -0400

    Merge pull request #348 from JPrause/ivanchukGA_cl
    
    [Changelog] Rollup of Ivanchuk releases
    
    (cherry picked from commit 24cbe112eea1afe059928b0e4d2ccd2c58c5da29)
```

**Pull request merged**
