### PR TITLE
Move from apache module mod_auth_kerb to mod_auth_gssapi

### PR DESCRIPTION
**Pull request by jvlcek**
https://www.pivotaltracker.com/n/projects/1610127/stories/160659028

This PR is one of a set that will implement moving external authentication support from
the Apache module mod_auth_kerb to mod_auth_gssapi

Once all of the PRs are available I will remove the WIP flag

### CODE REVIEW

**Comment by jvlcek** [comment]
@miq-bot add_label wip

**Comment by jvlcek** [comment]
@miq-bot add_label enhancement

**Comment by jvlcek** [comment]
@miq-bot add_label hammer/yes

**Comment by jvlcek** [comment]
@gtanzillo and @abellotti I have made the update we agreed to yesterday. This should be good to go now.

**Comment by jvlcek** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1636547 will be used to track this work.

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 9fe5cc5a44d08890934058c8aee086c15dbb7d69
Author: Gregg Tanzillo <gtanzill@redhat.com>
Date:   Fri Oct 5 16:39:04 2018 -0400

    Merge pull request #282 from jvlcek/gssapi
    
    Move from apache module mod_auth_kerb to mod_auth_gssapi
    
    (cherry picked from commit 9ab682c2641fa2384b0d4d4836b23f6a203d4c5f)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1636547
```

**Pull request merged**
