### PR TITLE
Install ansible and python-boto for running ansible-playbook

### PR DESCRIPTION
**Pull request by simaishi**
For https://github.com/ManageIQ/manageiq/pull/17564. Both packages are available in EPEL.

cc @Ladas

### CODE REVIEW

**Comment by Ladas** [comment]
Looks good :+1: 

Will we do more PRs for that packages needed by the other providers?

**Comment by simaishi** [comment]
@Ladas I'm not sure what other packages you're talking about... I'm adding the two you mentioned in https://github.com/ManageIQ/manageiq/pull/17564, and not aware of anything else needed!

**Comment by Ladas** [comment]
@simaishi right, we will need more, based on what other providers will need, lets revive the mail conversation about it

**Comment by carbonin** [comment]
@Ladas @simaishi do we still need this if we're moving to ansible-runner?

**Comment by Ladas** [comment]
@carbonin I think we can close this

- ansible-runner beats the ansible rpm
- python-boto is needed for AWS playbooks, but we will not be merging those

**Comment by carbonin** [comment]
Okay, closing for now until we decide what will be needed for runner.

Provider dependencies can probably be handled separately as well.

**Pull request closed without merging**
