### PR TITLE
Update to ovirt 4.3

### PR DESCRIPTION
**Pull request by simaishi**
4.3 is the current version and matches with what downstream build uses.

### CODE REVIEW

**Comment by carbonin** [comment]
Looks good to me, but I don't know anything about our ovirt dependencies. @agrare this okay?

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 3f58f5427186195786ef98c21ba939a4176a588e
Author: Nick Carboni <ncarboni@redhat.com>
Date:   Fri Aug 2 17:00:46 2019 -0400

    Merge pull request #334 from simaishi/ovirt43
    
    Update to ovirt 4.3
    
    (cherry picked from commit 3eb500486c06b1d0e5f8c24afa1b29a040dc2b91)
```

**Comment by NickLaMuro** [comment]
@simaishi I was looking at a 5.10.7 appliance today and noticed that we are on `4.2.9` on there.  I think we need to have this updated on `hammer` to work with ansible 2.8 now.

**Comment by simaishi** [comment]
@NickLaMuro 5.10.9 and later uses 4.3.x. Upstream and downstream are handled differently and downstream gets updated packages automatically.

**Pull request merged**
