### PR TITLE
Install cockpit-ssh now that it is available

### PR DESCRIPTION
**Pull request by petervo**

### CODE REVIEW

**Comment by carbonin** [comment]
Can you explain why this is needed or what functionality is being added by adding this package?

**Comment by petervo** [comment]
@carbonin this is required to make the cockpit integration work. It was commented out before while waiting for it to reach rhel/centos.

**Comment by carbonin** [comment]
So then this will have to wait for centos 7.4 to be released, correct?

**Comment by simon3z** [comment]
Gregg I am assigning this to you for visibility. Cockpit integration is blocked on this.

@miq-bot assign gtanzillo

**Comment by petervo** [comment]
@carbonin, it arrived in 7.3 as part of cockpit 141

**Pull request merged**
