### PR TITLE
Align repo names with the official names

### PR DESCRIPTION
**Pull request by Fryguy**
Follow up to https://github.com/ManageIQ/manageiq-appliance/pull/293

@simaishi Please review.

### CODE REVIEW

**Comment by Fryguy** [comment]
Only one I'm not sure about is `google-cloud-compute`...do you know what's in the .repo file for that one?

**Comment by simaishi** [comment]
> Only one I'm not sure about is `google-cloud-compute`...do you know what's in the .repo file for that one?

We specify the repo name for post installation (as we have to manually create the repo file): https://github.com/ManageIQ/manageiq-appliance-build/blob/master/kickstarts/partials/post/repos.ks.erb

**Review by simaishi — APPROVED** [review]

**Comment by simaishi** [comment]
Looks good, just need change for gce (google-compute-engine vs google-cloud-compute)

**Comment by Fryguy** [comment]
@simaishi Updated.

**Review by simaishi — APPROVED** [review]

**Comment by simaishi** [comment]
Jansa backport details:

```
$ git log -1
commit 36770d83dd0db8eb1eb4fb44f863848851449c95
Author: Satoe Imaishi <simaishi@redhat.com>
Date:   Wed Sep 16 11:12:24 2020 -0400

    Merge pull request #439 from Fryguy/align_names

    Align repo names with the official names

    (cherry picked from commit bec064ece6146a9877bfb91c609609a741836419)
```

**Pull request merged**
